[[constraint]]
  name = "github.com/GeertJohan/go.rice"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/bitrise"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/envman"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/go-utils"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/goinp"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/stepman"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-tools/gows"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"
